Add test/Fold.hs
If we switch to PostgreSQL parameterized queries in the future,
this will break:

    query conn "FETCH FORWARD ? FROM fold" (Only chunkSize)

PostgreSQL doesn't support parameter substitution here:

    > FETCH FORWARD $1 FROM c;
    ERROR:  syntax error at or near "$1"
    LINE 1: FETCH FORWARD $1 FROM c;

postgresql-simple constructs the query string itself, so this
works for now.